### ISSUE TITLE
勘误: 章节2.3.2, 页码19

### ISSUE THREAD

**Issue by CCxiaoy** [jslib-book/jslib-book-code#15]
'npm i --save-dev rollup@0.57.1' 安装的rollup是指定为0.57.1
而在章节2.4.3, 页码30 'npm install --save-dev rollup-plugin-babel@4.0.3 @babel/core@7.1.2 @babel/preset-env@7.1.0'
会遇到 npm ERR! peer rollup@">=0.60.0 <1" from rollup-plugin-babel@4.0.3
所以建议将 rollup的版本升级来解决
个人是改为 rollup@0.67.0

详细terminal信息为
xiaoycc@xiaoyccdeMacBook-Air javascript-lib-practice % npm install --save-dev rollup-plugin-babel@4.0.3 @babel/core@7.1.2 @babel/preset-env@7.1.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: javascript-lib-practice@1.0.0
npm ERR! Found: rollup@0.57.1
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^0.57.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.60.0 <1" from rollup-plugin-babel@4.0.3
npm ERR! node_modules/rollup-plugin-babel
npm ERR!   dev rollup-plugin-babel@"4.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/xiaoycc/.npm/_logs/2023-02-27T08_32_51_552Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaoycc/.npm/_logs/2023-02-27T08_32_51_552Z-debug-0.log

**Comment by yanhaijing** [comment]
node版本和npm版本是啥？

**Comment by CCxiaoy** [comment]
node 19.7.0
npm 9.5.1

**Comment by yanhaijing** [comment]
本书需要使用node 14，其他版本可能存在各种问题，未验证过

**Comment by CCxiaoy** [comment]
好的，谢谢大佬，之前没有意识到这点，不好意思

**Comment by yanhaijing** [comment]
换成node14吧，快速学到知识，别被这种兼容坑给拖累了，^_^
