### ISSUE TITLE
勘误：章节 6.2.2，页码 130页，omit 函数勘误

### ISSUE THREAD

**Issue by xiong-ling** [jslib-book/jslib-book-code#6]
勘误范围：第一版印刷

在130页，6.2.2 节 omit 函数写的有点问题，应该是 delete data[key] 吧
![11](https://user-images.githubusercontent.com/52132077/212611691-e71e5fca-c88c-4744-8b61-22bff21cd414.jpg)

**Comment by yanhaijing** [comment]
是的
